<link rel="shortcut icon" type="image/png" href="{{ "/favicon.png"  | absolute_url }}">
theme: minima
title: Shilin's Blog
author: Shilin
description: > # this means to ignore newlines until "baseurl:"
  Shilin's personal blog site where she talks about blockchian, bitcoin, products, and life nonsense.
# social links
twitter_username: CryptoShilin # DO NOT include the @ character, or else the build will fail!
github_username:  Zheng-Shilin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
